MOODY_LYRICS_DOWNLOAD_URL = "http://softeng.polito.it/erion/MoodyLyrics.zip"
MOODY_LYRICS_PATH = "MoodyLyrics"
MOODY_LYRICS_FILE_TEMPLATE = "ml_{}.xlsx"
NJU_MUSIC_MOOD_DOWNLOAD_URL = "http://cs.nju.edu.cn/sufeng/data/NJU_MusicMood_v1.zip"
NJU_MUSIC_MOOD_PATH = "NJU_MusicMood_v1.0"
OVH_URL = "https://api.lyrics.ovh/v1"
OUTPUT_DATA_PATH = "lyrics.csv"
